//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AprendizProcessInstructor
    {
        public int Id { get; set; }
    
        public virtual Aprendiz AprendizId { get; set; }
        public virtual Instructor InstructorId { get; set; }
        public virtual RegisterySofia RegisterySofiaId { get; set; }
        public virtual Concept ConceptId { get; set; }
        public virtual Enterprise EnterpriseId { get; set; }
        public virtual TypeModality TypeModalityId { get; set; }
        public virtual State StateId { get; set; }
        public virtual Verification VerificationId { get; set; }
        public virtual Process ProcessId { get; set; }
    }
}
