//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbAutogestionContainer : DbContext
    {
        public DbAutogestionContainer()
            : base("name=DbAutogestionContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Form> FormSet { get; set; }
        public virtual DbSet<FormModule> FormModuleSet { get; set; }
        public virtual DbSet<Module> ModuleSet { get; set; }
        public virtual DbSet<RolForm> RolFormSet { get; set; }
        public virtual DbSet<Rol> RolSet { get; set; }
        public virtual DbSet<UserRol> UserRolSet { get; set; }
        public virtual DbSet<Person> PersonSet1 { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<UserSede> UserSedeSet1 { get; set; }
        public virtual DbSet<Sede> SedeSet { get; set; }
        public virtual DbSet<Regional> RegionalSet { get; set; }
        public virtual DbSet<Aprendiz> AprendizSet1 { get; set; }
        public virtual DbSet<Program> ProgramSet { get; set; }
        public virtual DbSet<AprendizProgram> AprendizProgramSet { get; set; }
        public virtual DbSet<Instructor> InstructorSet { get; set; }
        public virtual DbSet<TypeModality> TypeModalitySet { get; set; }
        public virtual DbSet<RegisterySofia> RegisterySofiaSet { get; set; }
        public virtual DbSet<Concept> ConceptSet { get; set; }
        public virtual DbSet<Enterprise> EnterpriseSet { get; set; }
        public virtual DbSet<Process> ProcessSet { get; set; }
        public virtual DbSet<AprendizProcessInstructor> AprendizProcessInstructorSet { get; set; }
        public virtual DbSet<State> StateSet1 { get; set; }
        public virtual DbSet<Verification> VerificationSet1 { get; set; }
        public virtual DbSet<InstructorProgram> instructors_programs { get; set; }
        public virtual DbSet<change_log> change_logs { get; set; }
        public virtual DbSet<Center> CenterSet { get; set; }
    }
}
