//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram2
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstructorProgram
    {
        public int Id { get; set; }
    
        public virtual Instructor InstructorId { get; set; }
        public virtual Program ProgramId { get; set; }
    }
}
