//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Program()
        {
            this.AprendizProgram = new HashSet<AprendizProgram>();
            this.InstructorProgram = new HashSet<InstructorProgram>();
        }
    
        public int Id { get; set; }
        public decimal CodeProgram { get; set; }
        public string Name { get; set; }
        public string TypeProgram { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime DeleteDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool Active { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AprendizProgram> AprendizProgram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstructorProgram> InstructorProgram { get; set; }
    }
}
