//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sede
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sede()
        {
            this.PersonSede = new HashSet<UserSede>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public long CodeSede { get; set; }
        public string Address { get; set; }
        public short PhoneSede { get; set; }
        public string EmailContact { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime DeleteDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int CenterId1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSede> PersonSede { get; set; }
        public virtual Center CenterId { get; set; }
    }
}
