//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram2
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSede
    {
        public int Id { get; set; }
        public int StatusProcedure { get; set; }
    
        public virtual Sede SedeId { get; set; }
        public virtual User UserId { get; set; }
    }
}
